[project]
name = "report_generator"
version = "0.1.0"
description = "Скрипт для создания отчетов по .csv файлам."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.2",
    "tabulate>=0.9.0",
]
